CREATE TABLE .CustomerRaw (
    ID INT PRIMARY KEY,
    Client_Income FLOAT,
    Car_Owned INT, -- 0 = No, 1 = Yes
    Bike_Owned INT,
    Active_Loan INT,
    House_Own INT,
    Child_Count INT,
    Credit_Amount FLOAT,
    Loan_Annuity FLOAT,
    Accompany_Client VARCHAR(255),
    Client_Income_Type VARCHAR(255),
    Client_Education VARCHAR(255),
    Client_Marital_Status VARCHAR(255),
    Client_Gender VARCHAR(50),
    Loan_Contract_Type VARCHAR(50),
    Client_Housing_Type VARCHAR(255),
    Population_Region_Relative FLOAT,
    Age_Days FLOAT,
    Employed_Days FLOAT,
    Registration_Days FLOAT,
    ID_Days FLOAT,
    Own_House_Age FLOAT,
    Mobile_Tag INT, -- Boolean Replacement
    Homephone_Tag INT,
    Workphone_Working INT,
    Client_Occupation VARCHAR(255),
    Client_Family_Members INT,
    Client_City_Rating FLOAT,
    Application_Process_Day INT,
    Application_Process_Hour INT,
    Client_Permanent_Match_Tag VARCHAR(50),
    Client_Contact_Work_Tag VARCHAR(50),
    Type_Organization VARCHAR(255),
    Score_Source_1 FLOAT,
    Score_Source_2 FLOAT,
    Score_Source_3 FLOAT,
    Social_Circle_Default FLOAT,
    Phone_Change FLOAT,
    Credit_Bureau FLOAT,
    Defaulters INT -- Boolean Replacement (0 = No Default, 1 = Defaulted)
);


